/**
 * generated by Xtext 2.18.0.M3
 */
package graphmodelgenerator.generator;

import com.google.common.base.Objects;
import com.google.common.collect.Iterables;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.ExclusiveRange;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.Functions.Function2;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.MapExtensions;
import org.omg.sysml.lang.sysml.ActionDefinition;
import org.omg.sysml.lang.sysml.ActionUsage;
import org.omg.sysml.lang.sysml.AttributeDefinition;
import org.omg.sysml.lang.sysml.AttributeUsage;
import org.omg.sysml.lang.sysml.DecisionNode;
import org.omg.sysml.lang.sysml.Element;
import org.omg.sysml.lang.sysml.EnumerationDefinition;
import org.omg.sysml.lang.sysml.EnumerationUsage;
import org.omg.sysml.lang.sysml.Expression;
import org.omg.sysml.lang.sysml.LiteralInfinity;
import org.omg.sysml.lang.sysml.LiteralInteger;
import org.omg.sysml.lang.sysml.Membership;
import org.omg.sysml.lang.sysml.MergeNode;
import org.omg.sysml.lang.sysml.Multiplicity;
import org.omg.sysml.lang.sysml.MultiplicityRange;
import org.omg.sysml.lang.sysml.Namespace;
import org.omg.sysml.lang.sysml.PartDefinition;
import org.omg.sysml.lang.sysml.PartUsage;
import org.omg.sysml.lang.sysml.Subclassification;
import org.omg.sysml.lang.sysml.SuccessionAsUsage;
import org.omg.sysml.lang.sysml.TransitionUsage;
import org.omg.sysml.lang.sysml.Usage;

@SuppressWarnings("all")
public class SysMLGeneratorAlloy extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _get = resource.getContents().get(0);
    final Namespace model = ((Namespace) _get);
    final String name = resource.getURI().trimFileExtension().lastSegment();
    fsa.generateFile((name + ".als"), IFileSystemAccess2.DEFAULT_OUTPUT, this.generate(model));
  }
  
  public String generate(final Namespace model) {
    StringConcatenation _builder = new StringConcatenation();
    {
      Iterable<org.omg.sysml.lang.sysml.Package> _filter = Iterables.<org.omg.sysml.lang.sysml.Package>filter(model.getMember(), org.omg.sysml.lang.sysml.Package.class);
      for(final org.omg.sysml.lang.sysml.Package p : _filter) {
        {
          EList<Membership> _importedMembership = p.getImportedMembership();
          for(final Membership i : _importedMembership) {
            _builder.append("sig ");
            String _name = i.getMemberElement().getName();
            _builder.append(_name);
            _builder.append(" {}");
            _builder.newLineIfNotEmpty();
            _builder.append("\t\t");
            _builder.newLine();
          }
        }
        {
          Iterable<PartDefinition> _filter_1 = Iterables.<PartDefinition>filter(p.getMember(), PartDefinition.class);
          for(final PartDefinition pd : _filter_1) {
            String _partDefinition = this.partDefinition(pd);
            _builder.append(_partDefinition);
            _builder.newLineIfNotEmpty();
            _builder.newLine();
          }
        }
        {
          Iterable<AttributeDefinition> _filter_2 = Iterables.<AttributeDefinition>filter(p.getMember(), AttributeDefinition.class);
          for(final AttributeDefinition ad : _filter_2) {
            String _attributeDefinition = this.attributeDefinition(ad);
            _builder.append(_attributeDefinition);
            _builder.newLineIfNotEmpty();
            _builder.newLine();
          }
        }
      }
    }
    {
      boolean _isEmpty = IterableExtensions.isEmpty(Iterables.<ActionDefinition>filter(model.getMember(), ActionDefinition.class));
      boolean _not = (!_isEmpty);
      if (_not) {
        String _abstractAction = this.abstractAction();
        _builder.append(_abstractAction);
        _builder.newLineIfNotEmpty();
        _builder.newLine();
      }
    }
    {
      Iterable<ActionDefinition> _filter_3 = Iterables.<ActionDefinition>filter(model.getMember(), ActionDefinition.class);
      for(final ActionDefinition ad_1 : _filter_3) {
        String _actionDefinition = this.actionDefinition(ad_1);
        _builder.append(_actionDefinition);
        _builder.newLineIfNotEmpty();
      }
    }
    {
      boolean _isEmpty_1 = IterableExtensions.isEmpty(Iterables.<ActionDefinition>filter(model.getMember(), ActionDefinition.class));
      boolean _not_1 = (!_isEmpty_1);
      if (_not_1) {
        _builder.newLine();
        _builder.append("run {} for ");
        int _numOfNodes = this.numOfNodes(Iterables.<ActionDefinition>filter(model.getMember(), ActionDefinition.class));
        _builder.append(_numOfNodes);
        _builder.append(" Action");
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder.toString();
  }
  
  public String partDefinition(final PartDefinition pd) {
    StringConcatenation _builder = new StringConcatenation();
    {
      boolean _isAbstract = pd.isAbstract();
      if (_isAbstract) {
        _builder.append("abstract sig ");
        String _name = pd.getName();
        _builder.append(_name);
      } else {
        _builder.newLineIfNotEmpty();
        _builder.append("sig ");
        String _name_1 = pd.getName();
        _builder.append(_name_1);
      }
    }
    final EList<Subclassification> super_types = pd.getOwnedSubclassification();
    {
      int _size = super_types.size();
      boolean _notEquals = (_size != 0);
      if (_notEquals) {
        _builder.append(" extends ");
        String _name_2 = super_types.get(0).getSuperclassifier().getName();
        _builder.append(_name_2);
        {
          int _size_1 = super_types.size();
          ExclusiveRange _doubleDotLessThan = new ExclusiveRange(1, _size_1, true);
          for(final Integer i : _doubleDotLessThan) {
            _builder.append(", ");
            String _name_3 = super_types.get((i).intValue()).getSuperclassifier().getName();
            _builder.append(_name_3);
          }
        }
      }
    }
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    {
      Iterable<PartUsage> _filter = Iterables.<PartUsage>filter(pd.getOwnedPart(), PartUsage.class);
      for(final PartUsage pu : _filter) {
        _builder.append("\t");
        String _partUsage = this.partUsage(pu);
        _builder.append(_partUsage);
        String _lineEnd = this.lineEnd(Iterables.<PartUsage>filter(pd.getOwnedPart(), PartUsage.class), pu);
        _builder.append(_lineEnd);
        _builder.newLineIfNotEmpty();
      }
    }
    {
      Iterable<AttributeUsage> _filter_1 = Iterables.<AttributeUsage>filter(pd.getOwnedAttribute(), AttributeUsage.class);
      for(final AttributeUsage attr : _filter_1) {
        _builder.append("\t");
        String _attributeUsage = this.attributeUsage(attr);
        _builder.append(_attributeUsage);
        String _lineEnd_1 = this.lineEnd(Iterables.<AttributeUsage>filter(pd.getOwnedAttribute(), AttributeUsage.class), attr);
        _builder.append(_lineEnd_1);
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("}");
    {
      boolean _isEmpty = this.multiplicityConstraints(Iterables.<PartUsage>filter(pd.getOwnedPart(), PartUsage.class), Iterables.<AttributeUsage>filter(pd.getOwnedAttribute(), AttributeUsage.class)).isEmpty();
      boolean _not = (!_isEmpty);
      if (_not) {
        _builder.append(" {");
        _builder.newLineIfNotEmpty();
        {
          List<String> _multiplicityConstraints = this.multiplicityConstraints(Iterables.<PartUsage>filter(pd.getOwnedPart(), PartUsage.class), Iterables.<AttributeUsage>filter(pd.getOwnedAttribute(), AttributeUsage.class));
          for(final String c : _multiplicityConstraints) {
            _builder.append("\t");
            _builder.append(c, "\t");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("}");
        _builder.newLine();
      }
    }
    return _builder.toString();
  }
  
  public String partUsage(final PartUsage pu) {
    StringConcatenation _builder = new StringConcatenation();
    String _name = pu.getName();
    _builder.append(_name);
    _builder.append(": ");
    {
      Multiplicity _multiplicity = pu.getMultiplicity();
      if ((_multiplicity instanceof MultiplicityRange)) {
        Multiplicity _multiplicity_1 = pu.getMultiplicity();
        String _multiplicity_2 = this.multiplicity(((MultiplicityRange) _multiplicity_1));
        _builder.append(_multiplicity_2);
      }
    }
    String _name_1 = pu.getDefinition().get(0).getName();
    _builder.append(_name_1);
    return _builder.toString();
  }
  
  public String attributeUsage(final AttributeUsage attr) {
    StringConcatenation _builder = new StringConcatenation();
    String _name = attr.getName();
    _builder.append(_name);
    _builder.append(": ");
    {
      Multiplicity _multiplicity = attr.getMultiplicity();
      if ((_multiplicity instanceof MultiplicityRange)) {
        Multiplicity _multiplicity_1 = attr.getMultiplicity();
        String _multiplicity_2 = this.multiplicity(((MultiplicityRange) _multiplicity_1));
        _builder.append(_multiplicity_2);
      }
    }
    String _attributeType = this.attributeType(attr.getDefinition().get(0).getName());
    _builder.append(_attributeType);
    return _builder.toString();
  }
  
  public String attributeDefinition(final AttributeDefinition ad) {
    StringConcatenation _builder = new StringConcatenation();
    {
      if ((ad instanceof EnumerationDefinition)) {
        _builder.append("enum ");
        String _name = ((EnumerationDefinition)ad).getName();
        _builder.append(_name);
        _builder.append(" {");
        _builder.newLineIfNotEmpty();
        final Iterable<EnumerationUsage> enum_values = Iterables.<EnumerationUsage>filter(((EnumerationDefinition)ad).getMember(), EnumerationUsage.class);
        {
          int _size = IterableExtensions.size(enum_values);
          boolean _notEquals = (_size != 0);
          if (_notEquals) {
            _builder.append("\t");
            String _name_1 = (((EnumerationUsage[])Conversions.unwrapArray(enum_values, EnumerationUsage.class))[0]).getName();
            _builder.append(_name_1);
            {
              int _size_1 = IterableExtensions.size(enum_values);
              ExclusiveRange _doubleDotLessThan = new ExclusiveRange(1, _size_1, true);
              for(final Integer i : _doubleDotLessThan) {
                _builder.append(", ");
                String _name_2 = (((EnumerationUsage[])Conversions.unwrapArray(enum_values, EnumerationUsage.class))[(i).intValue()]).getName();
                _builder.append(_name_2);
              }
            }
          }
        }
        _builder.newLineIfNotEmpty();
      } else {
        _builder.append("sig ");
        String _name_3 = ad.getName();
        _builder.append(_name_3);
        _builder.append(" {");
        _builder.newLineIfNotEmpty();
      }
    }
    {
      Iterable<AttributeUsage> _filter = Iterables.<AttributeUsage>filter(ad.getOwnedAttribute(), AttributeUsage.class);
      for(final AttributeUsage au : _filter) {
        _builder.append("\t");
        String _name_4 = au.getName();
        _builder.append(_name_4);
        _builder.append(": ");
        {
          Multiplicity _multiplicity = au.getMultiplicity();
          if ((_multiplicity instanceof MultiplicityRange)) {
            Multiplicity _multiplicity_1 = au.getMultiplicity();
            String _multiplicity_2 = this.multiplicity(((MultiplicityRange) _multiplicity_1));
            _builder.append(_multiplicity_2);
          }
        }
        String _attributeType = this.attributeType(au.getDefinition().get(0).getName());
        _builder.append(_attributeType);
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("}");
    {
      boolean _isEmpty = this.multiplicityConstraints(Collections.<PartUsage>emptyList(), Iterables.<AttributeUsage>filter(ad.getOwnedAttribute(), AttributeUsage.class)).isEmpty();
      boolean _not = (!_isEmpty);
      if (_not) {
        _builder.append(" {");
        _builder.newLineIfNotEmpty();
        {
          List<String> _multiplicityConstraints = this.multiplicityConstraints(Collections.<PartUsage>emptyList(), Iterables.<AttributeUsage>filter(ad.getOwnedAttribute(), AttributeUsage.class));
          for(final String c : _multiplicityConstraints) {
            _builder.append("\t");
            _builder.append(c, "\t");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("}");
        _builder.newLine();
      }
    }
    return _builder.toString();
  }
  
  public String multiplicity(final MultiplicityRange mr) {
    StringConcatenation _builder = new StringConcatenation();
    final Expression l_bound = mr.getLowerBound();
    final Expression u_bound = mr.getUpperBound();
    final Expression bound = mr.getBound().get(0);
    {
      if (((l_bound != null) && (u_bound != null))) {
        {
          if (((((l_bound instanceof LiteralInteger) && (u_bound instanceof LiteralInteger)) && (((LiteralInteger) l_bound).getValue() == 0)) && (((LiteralInteger) l_bound).getValue() == 1))) {
            _builder.append("lone ");
          }
        }
        {
          if (((l_bound instanceof LiteralInteger) && (((LiteralInteger) l_bound).getValue() == 0))) {
            _builder.append("set ");
          } else {
            _builder.append("some ");
          }
        }
      } else {
        if ((bound != null)) {
          {
            if ((bound instanceof LiteralInfinity)) {
              _builder.append("set ");
            } else {
              if (((bound instanceof LiteralInteger) && (((LiteralInteger) bound).getValue() != 1))) {
                _builder.append("some ");
              }
            }
          }
        }
      }
    }
    return _builder.toString();
  }
  
  public String attributeType(final String type) {
    StringConcatenation _builder = new StringConcatenation();
    {
      boolean _equals = type.equals("Integer");
      if (_equals) {
        _builder.append("Integer ");
      } else {
        boolean _equals_1 = type.equals("UnlimitedNatural");
        if (_equals_1) {
          _builder.append("UnlimitedNatural ");
        } else {
          boolean _equals_2 = type.equals("String");
          if (_equals_2) {
            _builder.append("String ");
          } else {
            boolean _equals_3 = type.equals("Real");
            if (_equals_3) {
              _builder.append("Real ");
            } else {
              boolean _equals_4 = type.equals("Boolean");
              if (_equals_4) {
                _builder.append("Boolean ");
              } else {
                _builder.append(type);
                _builder.append(" ");
              }
            }
          }
        }
      }
    }
    return _builder.toString();
  }
  
  public String lineEnd(final Iterable<PartUsage> parts, final PartUsage pu) {
    StringConcatenation _builder = new StringConcatenation();
    {
      boolean _equals = pu.equals(IterableExtensions.<PartUsage>last(parts));
      boolean _not = (!_equals);
      if (_not) {
        _builder.append(",");
      }
    }
    return _builder.toString();
  }
  
  public String lineEnd(final Iterable<AttributeUsage> attributes, final AttributeUsage attr) {
    StringConcatenation _builder = new StringConcatenation();
    {
      boolean _equals = attr.equals(IterableExtensions.<AttributeUsage>last(attributes));
      boolean _not = (!_equals);
      if (_not) {
        _builder.append(",");
      }
    }
    return _builder.toString();
  }
  
  public List<String> multiplicityConstraints(final Iterable<PartUsage> partUsages, final Iterable<AttributeUsage> attrUsages) {
    final List<Usage> usages = new ArrayList<Usage>();
    Iterables.<Usage>addAll(usages, partUsages);
    Iterables.<Usage>addAll(usages, attrUsages);
    final ArrayList<String> constraints = new ArrayList<String>();
    for (final Usage u : usages) {
      Multiplicity _multiplicity = u.getMultiplicity();
      if ((_multiplicity instanceof MultiplicityRange)) {
        Multiplicity _multiplicity_1 = u.getMultiplicity();
        final Expression l_bound = ((MultiplicityRange) _multiplicity_1).getLowerBound();
        Multiplicity _multiplicity_2 = u.getMultiplicity();
        final Expression u_bound = ((MultiplicityRange) _multiplicity_2).getUpperBound();
        Multiplicity _multiplicity_3 = u.getMultiplicity();
        final Expression bound = ((MultiplicityRange) _multiplicity_3).getBound().get(0);
        if (((!Objects.equal(l_bound, null)) && (!Objects.equal(u_bound, null)))) {
          if ((((l_bound instanceof LiteralInteger) && (((LiteralInteger) l_bound).getValue() != 0)) && (((LiteralInteger) l_bound).getValue() != 1))) {
            String _name = u.getName();
            String _plus = ("#" + _name);
            String _plus_1 = (_plus + " >= ");
            int _value = ((LiteralInteger) l_bound).getValue();
            String _plus_2 = (_plus_1 + Integer.valueOf(_value));
            constraints.add(_plus_2);
          }
          if ((u_bound instanceof LiteralInteger)) {
            String _name_1 = u.getName();
            String _plus_3 = ("#" + _name_1);
            String _plus_4 = (_plus_3 + " <= ");
            int _value_1 = ((LiteralInteger) u_bound).getValue();
            String _plus_5 = (_plus_4 + Integer.valueOf(_value_1));
            constraints.add(_plus_5);
          }
        } else {
          if ((((!Objects.equal(bound, null)) && (bound instanceof LiteralInteger)) && (((LiteralInteger) bound).getValue() != 1))) {
            String _name_2 = u.getName();
            String _plus_6 = ("#" + _name_2);
            String _plus_7 = (_plus_6 + " = ");
            int _value_2 = ((LiteralInteger) bound).getValue();
            String _plus_8 = (_plus_7 + Integer.valueOf(_value_2));
            constraints.add(_plus_8);
          }
        }
      }
    }
    return constraints;
  }
  
  public String abstractAction() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("abstract sig Action {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("next: lone Action");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
  
  public String actionDefinition(final ActionDefinition ad) {
    StringConcatenation _builder = new StringConcatenation();
    {
      boolean _isEmpty = ad.getOwnedAction().isEmpty();
      boolean _not = (!_isEmpty);
      if (_not) {
        {
          EList<ActionUsage> _ownedAction = ad.getOwnedAction();
          for(final ActionUsage au : _ownedAction) {
            {
              if ((!(au instanceof TransitionUsage))) {
                _builder.append("sig ");
                String _actionDefName = this.actionDefName(au);
                _builder.append(_actionDefName);
                _builder.append(" extends Action {}");
                _builder.newLineIfNotEmpty();
              }
            }
          }
        }
        {
          boolean _not_1 = (!(IterableExtensions.isEmpty(Iterables.<SuccessionAsUsage>filter(ad.getMember(), SuccessionAsUsage.class)) && IterableExtensions.isEmpty(Iterables.<TransitionUsage>filter(ad.getMember(), TransitionUsage.class))));
          if (_not_1) {
            _builder.newLine();
            String _actionConstraints = this.actionConstraints(ad);
            _builder.append(_actionConstraints);
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    return _builder.toString();
  }
  
  public String actionConstraints(final ActionDefinition ad) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("fact correctSuccession {");
    _builder.newLine();
    _builder.append("\t");
    String _correctSuccession = this.correctSuccession(Iterables.<SuccessionAsUsage>filter(ad.getMember(), SuccessionAsUsage.class), Iterables.<TransitionUsage>filter(ad.getMember(), TransitionUsage.class));
    _builder.append(_correctSuccession, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    {
      boolean _hasEndAction = this.hasEndAction(ad);
      if (_hasEndAction) {
        _builder.append("fact numOfNext {");
        _builder.newLine();
        _builder.append("\t");
        String _numOfNext = this.numOfNext(ad, Iterables.<SuccessionAsUsage>filter(ad.getMember(), SuccessionAsUsage.class), Iterables.<TransitionUsage>filter(ad.getMember(), TransitionUsage.class));
        _builder.append(_numOfNext, "\t");
        _builder.newLineIfNotEmpty();
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
      }
    }
    _builder.append("fact actionSeq {");
    _builder.newLine();
    _builder.append("\t");
    CharSequence _actionSeq = this.actionSeq(this.startActionDefName(ad));
    _builder.append(_actionSeq, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("fact lonePrev {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("all a: Action | (lone _a: Action | a in _a.next)");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
  
  public String correctSuccession(final Iterable<SuccessionAsUsage> successions, final Iterable<TransitionUsage> transitions) {
    StringConcatenation _builder = new StringConcatenation();
    {
      for(final SuccessionAsUsage succ : successions) {
        {
          boolean _justActionTargets = this.justActionTargets(succ);
          if (_justActionTargets) {
            _builder.append("all a: ");
            Element _get = succ.getSource().get(0);
            String _actionDefName = this.actionDefName(((ActionUsage) _get));
            _builder.append(_actionDefName);
            _builder.append(" | a.next in ");
            Element _get_1 = succ.getTarget().get(0);
            String _actionDefName_1 = this.actionDefName(((ActionUsage) _get_1));
            _builder.append(_actionDefName_1);
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    {
      Set<Map.Entry<ActionUsage, List<String>>> _entrySet = this.transitionMap(transitions, false).entrySet();
      for(final Map.Entry<ActionUsage, List<String>> entry : _entrySet) {
        _builder.append("all a: ");
        String _actionDefName_2 = this.actionDefName(entry.getKey());
        _builder.append(_actionDefName_2);
        _builder.append(" | a.next in ");
        {
          List<String> _value = entry.getValue();
          for(final String targetName : _value) {
            _builder.append(targetName);
            {
              boolean _equals = targetName.equals(IterableExtensions.<String>last(entry.getValue()));
              boolean _not = (!_equals);
              if (_not) {
                _builder.append(" + ");
              }
            }
          }
        }
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder.toString();
  }
  
  public String numOfNext(final ActionDefinition ad, final Iterable<SuccessionAsUsage> successions, final Iterable<TransitionUsage> transitions) {
    StringConcatenation _builder = new StringConcatenation();
    {
      for(final SuccessionAsUsage succ : successions) {
        {
          if ((this.justActionTargets(succ) && this.leadsToEndAction(ad, succ, new ArrayList<Usage>()))) {
            _builder.append("all a: ");
            Element _get = succ.getSource().get(0);
            String _actionDefName = this.actionDefName(((ActionUsage) _get));
            _builder.append(_actionDefName);
            _builder.append(" | (one _a: Action | _a in a.next)");
            _builder.newLineIfNotEmpty();
          } else {
            boolean _hasTargetEndAction = this.hasTargetEndAction(succ);
            if (_hasTargetEndAction) {
              _builder.append("all a: ");
              Element _get_1 = succ.getSource().get(0);
              String _actionDefName_1 = this.actionDefName(((ActionUsage) _get_1));
              _builder.append(_actionDefName_1);
              _builder.append(" | (no _a: Action | _a in a.next)");
              _builder.newLineIfNotEmpty();
            }
          }
        }
      }
    }
    final Map<ActionUsage, List<String>> actionTargetMap = this.oneTargetActionMap(ad, transitions);
    final Map<ActionUsage, List<String>> endTargetMap = this.justEndTargetMap(transitions);
    {
      Set<Map.Entry<ActionUsage, List<String>>> _entrySet = actionTargetMap.entrySet();
      for(final Map.Entry<ActionUsage, List<String>> entry : _entrySet) {
        _builder.newLineIfNotEmpty();
        _builder.append("all a: ");
        String _actionDefName_2 = this.actionDefName(entry.getKey());
        _builder.append(_actionDefName_2);
        _builder.append(" | (one _a: Action | _a in a.next)");
        _builder.newLineIfNotEmpty();
      }
    }
    {
      Set<Map.Entry<ActionUsage, List<String>>> _entrySet_1 = endTargetMap.entrySet();
      for(final Map.Entry<ActionUsage, List<String>> entry_1 : _entrySet_1) {
        _builder.append("all a: ");
        String _actionDefName_3 = this.actionDefName(entry_1.getKey());
        _builder.append(_actionDefName_3);
        _builder.append(" | (no _a: Action | _a in a.next)");
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder.toString();
  }
  
  public String actionDefName(final ActionUsage au) {
    StringConcatenation _builder = new StringConcatenation();
    {
      if ((au instanceof MergeNode)) {
        _builder.append("Merge_");
        String _name = ((MergeNode)au).getName();
        _builder.append(_name);
      } else {
        if ((au instanceof DecisionNode)) {
          _builder.append("Decision_");
          String _name_1 = ((DecisionNode)au).getName();
          _builder.append(_name_1);
        } else {
          String _name_2 = au.getDefinition().get(0).getName();
          _builder.append(_name_2);
        }
      }
    }
    return _builder.toString();
  }
  
  public String startActionDefName(final ActionDefinition ad) {
    StringConcatenation _builder = new StringConcatenation();
    {
      Iterable<SuccessionAsUsage> _filter = Iterables.<SuccessionAsUsage>filter(ad.getMember(), SuccessionAsUsage.class);
      for(final SuccessionAsUsage succ : _filter) {
        {
          if (((((((succ.getSource().get(0) instanceof ActionUsage) && (succ.getTarget().get(0) instanceof ActionUsage)) && (!Objects.equal(succ.getSource().get(0).getName(), null))) && succ.getSource().get(0).getName().equals("start")) && (!Objects.equal(succ.getTarget().get(0).getName(), null))) && (!succ.getTarget().get(0).getName().equals("done")))) {
            Element _get = succ.getTarget().get(0);
            String _actionDefName = this.actionDefName(((ActionUsage) _get));
            _builder.append(_actionDefName);
          }
        }
      }
    }
    return _builder.toString();
  }
  
  public String lineEnd(final Iterable<SuccessionAsUsage> successions, final SuccessionAsUsage succ, final boolean onlyBlock, final boolean ownActionsOnly) {
    StringConcatenation _builder = new StringConcatenation();
    {
      if ((onlyBlock && succ.equals(this.lastSuccession(successions, ownActionsOnly)))) {
        _builder.append(".");
      } else {
        _builder.append(";");
      }
    }
    return _builder.toString();
  }
  
  public String lineEnd(final Iterable<TransitionUsage> transitions, final TransitionUsage trans, final boolean ownActionsOnly) {
    StringConcatenation _builder = new StringConcatenation();
    {
      boolean _equals = trans.equals(this.lastTransition(transitions, ownActionsOnly));
      if (_equals) {
        _builder.append(".");
      } else {
        _builder.append(";");
      }
    }
    return _builder.toString();
  }
  
  public String lineEnd(final Map<ActionUsage, List<String>> transitionMap, final ActionUsage key, final boolean lastBlock) {
    StringConcatenation _builder = new StringConcatenation();
    {
      if ((lastBlock && key.equals(this.lastKeyInTransitionMap(transitionMap)))) {
        _builder.append(".");
      } else {
        _builder.append(";");
      }
    }
    return _builder.toString();
  }
  
  public SuccessionAsUsage lastSuccession(final Iterable<SuccessionAsUsage> successions, final boolean ownActionsOnly) {
    if ((!ownActionsOnly)) {
      return IterableExtensions.<SuccessionAsUsage>last(successions);
    }
    final Function1<SuccessionAsUsage, Boolean> _function = (SuccessionAsUsage it) -> {
      return Boolean.valueOf(((!Objects.equal(it.getTarget().get(0).getName(), null)) && (!it.getTarget().get(0).getName().equals("done"))));
    };
    final Iterable<SuccessionAsUsage> filtered = IterableExtensions.<SuccessionAsUsage>filter(successions, _function);
    return IterableExtensions.<SuccessionAsUsage>last(filtered);
  }
  
  public TransitionUsage lastTransition(final Iterable<TransitionUsage> transitions, final boolean ownActionsOnly) {
    if ((!ownActionsOnly)) {
      return IterableExtensions.<TransitionUsage>last(transitions);
    }
    final Function1<TransitionUsage, Boolean> _function = (TransitionUsage it) -> {
      return Boolean.valueOf(((!Objects.equal(it.getTarget().getName(), null)) && (!it.getTarget().getName().equals("done"))));
    };
    final Iterable<TransitionUsage> filtered = IterableExtensions.<TransitionUsage>filter(transitions, _function);
    return IterableExtensions.<TransitionUsage>last(filtered);
  }
  
  public CharSequence actionSeq(final String entryAction) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("one a: Action | (all _a: Action | _a != a <=> _a in a.^next) and a in ");
    _builder.append(entryAction);
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public Map<ActionUsage, List<String>> transitionMap(final Iterable<TransitionUsage> transitions, final boolean isEnd) {
    final Map<ActionUsage, List<String>> map = new HashMap<ActionUsage, List<String>>();
    for (final TransitionUsage trans : transitions) {
      if (((((((trans.getSource() instanceof ActionUsage) && (trans.getTarget() instanceof ActionUsage)) && (!Objects.equal(trans.getSource().getName(), null))) && (!trans.getSource().getName().equals("start"))) && (!Objects.equal(trans.getTarget().getName(), null))) && (((!isEnd) && (!trans.getTarget().getName().equals("done"))) || (isEnd && trans.getTarget().getName().equals("done"))))) {
        boolean _containsKey = map.containsKey(trans.getSource());
        boolean _not = (!_containsKey);
        if (_not) {
          ActionUsage _source = trans.getSource();
          ArrayList<String> _arrayList = new ArrayList<String>();
          map.put(_source, _arrayList);
        }
        map.get(trans.getSource()).add(this.actionDefName(trans.getTarget()));
      }
    }
    return map;
  }
  
  public Map<ActionUsage, List<String>> justEndTargetMap(final Iterable<TransitionUsage> transitions) {
    final Map<ActionUsage, List<String>> actionTargetMap = this.transitionMap(transitions, false);
    final Map<ActionUsage, List<String>> endTargetMap = this.transitionMap(transitions, true);
    final Function2<ActionUsage, List<String>, Boolean> _function = (ActionUsage k, List<String> v) -> {
      boolean _containsKey = actionTargetMap.containsKey(k);
      return Boolean.valueOf((!_containsKey));
    };
    return MapExtensions.<ActionUsage, List<String>>filter(endTargetMap, _function);
  }
  
  public Map<ActionUsage, List<String>> oneTargetActionMap(final ActionDefinition ad, final Iterable<TransitionUsage> transitions) {
    final Map<ActionUsage, List<String>> actionTargetMap = this.transitionMap(transitions, false);
    final Function2<ActionUsage, List<String>, Boolean> _function = (ActionUsage k, List<String> v) -> {
      return Boolean.valueOf(((v.size() > 1) && this.leadsToEndAction(ad, this.outEdges(ad, k).get(0), new ArrayList<Usage>())));
    };
    return MapExtensions.<ActionUsage, List<String>>filter(actionTargetMap, _function);
  }
  
  public ActionUsage lastKeyInTransitionMap(final Map<ActionUsage, List<String>> map) {
    ActionUsage key = null;
    Set<Map.Entry<ActionUsage, List<String>>> _entrySet = map.entrySet();
    for (final Map.Entry<ActionUsage, List<String>> entry : _entrySet) {
      key = entry.getKey();
    }
    return key;
  }
  
  public boolean justActionTargets(final SuccessionAsUsage succ) {
    if (((((((succ.getSource().get(0) instanceof ActionUsage) && (succ.getTarget().get(0) instanceof ActionUsage)) && (!Objects.equal(succ.getSource().get(0).getName(), null))) && (!succ.getSource().get(0).getName().equals("start"))) && (!Objects.equal(succ.getTarget().get(0).getName(), null))) && (!succ.getTarget().get(0).getName().equals("done")))) {
      return true;
    }
    return false;
  }
  
  public boolean hasTargetEndAction(final SuccessionAsUsage succ) {
    if (((((((succ.getSource().get(0) instanceof ActionUsage) && (succ.getTarget().get(0) instanceof ActionUsage)) && (!Objects.equal(succ.getSource().get(0).getName(), null))) && (!succ.getSource().get(0).getName().equals("start"))) && (!Objects.equal(succ.getTarget().get(0).getName(), null))) && succ.getTarget().get(0).getName().equals("done"))) {
      return true;
    }
    return false;
  }
  
  public boolean hasTargetEndAction(final TransitionUsage trans) {
    if (((((((trans.getSource() instanceof ActionUsage) && (trans.getTarget() instanceof ActionUsage)) && (!Objects.equal(trans.getSource().getName(), null))) && (!trans.getSource().getName().equals("start"))) && (!Objects.equal(trans.getTarget().getName(), null))) && trans.getTarget().getName().equals("done"))) {
      return true;
    }
    return false;
  }
  
  public boolean hasEndAction(final ActionDefinition ad) {
    Iterable<SuccessionAsUsage> _filter = Iterables.<SuccessionAsUsage>filter(ad.getMember(), SuccessionAsUsage.class);
    for (final SuccessionAsUsage succ : _filter) {
      boolean _hasTargetEndAction = this.hasTargetEndAction(succ);
      if (_hasTargetEndAction) {
        return true;
      }
    }
    Iterable<TransitionUsage> _filter_1 = Iterables.<TransitionUsage>filter(ad.getMember(), TransitionUsage.class);
    for (final TransitionUsage trans : _filter_1) {
      boolean _hasTargetEndAction_1 = this.hasTargetEndAction(trans);
      if (_hasTargetEndAction_1) {
        return true;
      }
    }
    return false;
  }
  
  public List<Usage> outEdges(final ActionDefinition ad, final Usage u) {
    final List<Usage> sources = new ArrayList<Usage>();
    Iterable<SuccessionAsUsage> _filter = Iterables.<SuccessionAsUsage>filter(ad.getMember(), SuccessionAsUsage.class);
    for (final SuccessionAsUsage succ : _filter) {
      boolean _equals = succ.getSource().get(0).equals(u);
      if (_equals) {
        sources.add(succ);
      }
    }
    Iterable<TransitionUsage> _filter_1 = Iterables.<TransitionUsage>filter(ad.getMember(), TransitionUsage.class);
    for (final TransitionUsage trans : _filter_1) {
      boolean _equals_1 = trans.getSource().equals(u);
      if (_equals_1) {
        sources.add(trans);
      }
    }
    return sources;
  }
  
  public boolean leadsToEndAction(final ActionDefinition ad, final Usage u, final List<Usage> seen) {
    if ((u instanceof SuccessionAsUsage)) {
      boolean _contains = seen.contains(u);
      if (_contains) {
        return false;
      } else {
        boolean _hasTargetEndAction = this.hasTargetEndAction(((SuccessionAsUsage) u));
        if (_hasTargetEndAction) {
          return true;
        } else {
          seen.add(u);
          Element _get = ((SuccessionAsUsage)u).getTarget().get(0);
          List<Usage> _outEdges = this.outEdges(ad, ((Usage) _get));
          for (final Usage e : _outEdges) {
            boolean _leadsToEndAction = this.leadsToEndAction(ad, e, seen);
            if (_leadsToEndAction) {
              return true;
            }
          }
          return false;
        }
      }
    } else {
      if ((u instanceof TransitionUsage)) {
        boolean _contains_1 = seen.contains(u);
        if (_contains_1) {
          return false;
        } else {
          boolean _hasTargetEndAction_1 = this.hasTargetEndAction(((TransitionUsage) u));
          if (_hasTargetEndAction_1) {
            return true;
          } else {
            seen.add(u);
            ActionUsage _target = ((TransitionUsage)u).getTarget();
            List<Usage> _outEdges_1 = this.outEdges(ad, ((Usage) _target));
            for (final Usage e_1 : _outEdges_1) {
              boolean _leadsToEndAction_1 = this.leadsToEndAction(ad, e_1, seen);
              if (_leadsToEndAction_1) {
                return true;
              }
            }
            return false;
          }
        }
      }
    }
    return false;
  }
  
  public int numOfNodes(final Iterable<ActionDefinition> actionDefs) {
    int cnt = 0;
    for (final ActionDefinition ad : actionDefs) {
      EList<ActionUsage> _ownedAction = ad.getOwnedAction();
      for (final ActionUsage au : _ownedAction) {
        if ((!(au instanceof TransitionUsage))) {
          int _cnt = cnt;
          cnt = (_cnt + 1);
        }
      }
    }
    return cnt;
  }
}
